### ISSUE TITLE
Add ability to reject chapters that are external links

### ISSUE THREAD

**Issue by cxr6548** [leotaku/kojirou#22]
`kojirou.exe -l en --autocrop --rank views-total a2febd3e-6252-46eb-bd63-01d51deaaec5 --dry-run`

Here is an example of a manga with problematic output. The links chosen for chapter 1-3 aren't hosted on MD and so don't make it into the final 0001.azw3 file - instead it simply starts at chapter 4.

I can work around this by specifying `--rank most` but I'd like either more fine-grain chapter selection or an automagic way to reject external links for chapters.

I don't think attempting to follow the links and download from there is a viable solution given that I can't even follow the link in my Firefox browser :/

**Comment by leotaku** [comment]
I've had a fix for this issue locally for quite some time, I just forgot to push it. The fix is now on master. I'll also create a new release with these fixes in the next few minutes. :)

As you've said, the only realistic fix here is just rejecting these "external" chapters, so that's what we now do.

**Comment by leotaku** [comment]
New release with prebuilt binaries is available, this should fix your issue. Thanks for reporting!
