### ISSUE TITLE
Feature Request: Limit speed

### ISSUE THREAD

**Issue by pahorema** [leotaku/kojirou#23]
Can we implement a feature to optionally limit the speed (or amount of requests) that we do to Mangadex?
Some manga have lots of chapters in the same volume (e.g Solo Leveling), and downloading the volume is impossible because Mangadex will get you (temporarily) banned.

A workaround is to download only a few chapters, use Calibre for converting them to Epub and merging them afterwards.
Still, it would be nice to download them directly in kojirou.

**Comment by pahorema** [comment]
Some examples:
01e01102-53d1-4bdf-847b-90cfe5b6415d (No volume, the only one containing english translations)
c0ee660b-f9f2-45c3-8068-5123ff53f84a (Volume 1)
596191eb-69ee-4401-983e-cc07e277fa17 (No volume)
32d76d19-8a05-4db0-9fc2-e0b0648fe9d0 (Volume 1)

All these have too many chapters in the same volume, I think this is the determining factor which results in a ban.

**Comment by pahorema** [comment]
Some examples:
01e01102-53d1-4bdf-847b-90cfe5b6415d (No volume, the only one containing english translations)
c0ee660b-f9f2-45c3-8068-5123ff53f84a (Volume 1)
596191eb-69ee-4401-983e-cc07e277fa17 (No volume)
32d76d19-8a05-4db0-9fc2-e0b0648fe9d0 (Volume 1)

All these have too many chapters in the same volume, I think this is the determining factor which results in a ban.

Sorry, I fucked up and closed accidentally the issue...

**Comment by leotaku** [comment]
I've tuned some of the rate limiting code. Please try running the application from the master branch.

I can't guarantee that you won't get rate-limited, because (according to a MangaDex developer I've spoken to) some rate limits are currently not publically documented, but with the latest changes timeouts and tempbans should be much more rare.

If you've found that this has solved your problem, feel free to close the issue. Otherwise, please send me IDs where you still experience problems.

**Comment by pahorema** [comment]
I think now it's fixed, got zero issues so far.
